const ALERT = "alert";
const REFETECH_CHATS = "refetch_chats";
const NEW_REQUEST = "new_request";
const NEW_MESSAGE_ALERT="new_message_alert"
const NEW_MESSAGE = "NEW_MESSAGE"
const NEW_GROUP_MESSAGE = "NEW_GROUP_MESSAGE"
const IS_TYPING = "Is_typing"
const STOP_TYPING = "Stop_Typing"
const InitialUsersStatus = "initialUsersStatus"
const USER_STATUS_CHANGE= "userStatusChange"
const MARK_MESSAGES_READ = "MARK_MESSAGES_READ"
const NEW_GROUP_MESSAGE_ALERT = "NEW_GROUP_MESSAGE_ALERT"
const MARK_GROUP_MESSAGES_READ = "MARK_GROUP_MESSAGES_READ"


export {
    NEW_GROUP_MESSAGE_ALERT, MARK_GROUP_MESSAGES_READ,MARK_MESSAGES_READ,InitialUsersStatus, NEW_GROUP_MESSAGE,USER_STATUS_CHANGE, IS_TYPING,STOP_TYPING,  ALERT ,NEW_MESSAGE, REFETECH_CHATS , NEW_REQUEST ,NEW_MESSAGE_ALERT 
}
